services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    ports:
      - 27017:27017 
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/etc:/etc/mongo